### ISSUE TITLE
Default zoom level option

### ISSUE THREAD

**Issue by HubKing** [cyotek/Cyotek.Windows.Forms.ImageBox#19]
There is "SizeMode" property. If you set it to "Fit", you cannot scroll or zoom the picture. If you set it to "Normal", you can scroll or zoom the picture, but when the picture is first loaded, if the image is big, only a portion of it shows with scroll bars.
I tried to call ZoomToFit() right after changing the Image, but then there is the split-second flickering of the image resizing (normal -> fit).
It would be helpful if in "Normal" "SizeMode", there was an option to make the image fit the control when first set. Most image viewer programmes I have used worked this way; they allowed zoom, but when the image is first loaded it fits the window.

**Comment by cyotek** [comment]
Hello,

Thanks for the feedback. I updated the General demonstration to do the image setting when the form was actually visible rather than when loaded and did observe a tiny bit of flicker.

However, there is a workaround you can use - call `BeginUpdate` prior to the two calls, and `EndUpdate` after. This will disable painting and scrollbar calculations until the `EndUpdate` call is made - I tested this and didn't observe any flicker of scrollbars.

      imageBox.BeginUpdate();
      imageBox.Image = image;
      imageBox.ZoomToFit();
      imageBox.EndUpdate();

Hope that helps!

Regards;
Richard Moss
