### ISSUE TITLE
Double click Event

### ISSUE THREAD

**Issue by Prakash19921206** [cyotek/Cyotek.Windows.Forms.ImageBox#25]
Hi
For `ImageBox`, i registered to `MouseDoubleClick `event, but for some reason event is not being raised.
however `MouseClick `(single click) event fires properly..
what could be the issue?

Thanks & Regards

**Comment by cyotek** [comment]
Hello,

This is actually by design - if you look in the constructor I disable double click support with the following line:

```c#
this.SetStyle(ControlStyles.StandardDoubleClick, false);
```

With that said, apparently I forgot to them hide the double click events so you couldn't hook them up easily :)

Off the top of my head I really can't remember why it was that double click was disabled. I just did some limited testing now and couldn't see anything obviously wrong - perhaps there was an issue in the original `ImageBox` implementation before the default scrollable control implementation was removed.

However, it's definitely something to look into changing if there's no obvious issues.

If you are using the source directly, then you can try commenting out the line directly. If you're using the NuGet package then you have at least two options - if you're inheriting from the `ImageBox` control then you can simply switch the style back on.

Or, you can hook into the `MouseClick` event and simulate a double click by using the [DateTime.Ticks](https://msdn.microsoft.com/en-us/library/system.datetime.ticks%28v=vs.110%29.aspx) property in conjunction with [SystemInformation.DoubleClickTime](https://msdn.microsoft.com/en-us/library/system.windows.forms.systeminformation.doubleclicktime(v=vs.110).aspx) to do your own double click detection.

```c#
long _doubleClickTimer;

private void imageBox_MouseClick(object sender, MouseEventArgs e)
{
  long ticks;

  ticks = DateTime.Now.Ticks;

  if (_doubleClickTimer == 0)
  {
    // first click
    _doubleClickTimer = ticks;
  }
  else
  {
    long millisecondsSinceLastClick;

    // calculate how long, in milliseconds, it was since the last click
    // (there are 10000 ticks per millisecond)
    millisecondsSinceLastClick = (ticks - _doubleClickTimer) / 10000;

    // reset the timer ready to initialize the next click
    _doubleClickTimer = 0;

    // if the number of milliseconds since the last click is less than the
    // system double click time, then we have a double click
    if (millisecondsSinceLastClick <= SystemInformation.DoubleClickTime)
    {
      // double click!
      // TODO: Check mouse buttons if you only want to use left etc
      Debug.WriteLine("Got a double click!");
    }
  }
}
```

Hope this helps!

Regards;
Richard Moss

**Comment by Prakash19921206** [comment]
Thanks for the quick reply! 
i commented the constructor and rebuilt the project. its working now :)
Thank you
