### ISSUE TITLE
Swipe support?

### ISSUE THREAD

**Issue by a1880** [cyotek/Cyotek.Windows.Forms.ImageBox#32]
I am using the ImageBox control for my (non-commercial) picture viewer application.
It works great and was fairly easy to implement (once I discovered that Image objects have to be "Dispose"d to avoid memory overflow).
It would be nice to get swipe support, even under Windows 7.
Currently, I navigate between the pictures via mouse clicks.

Any hints or ideas?

**Comment by cyotek** [comment]
Hello,

This sounds like a pretty interesting idea, although it might be a bit too niche to be a core part of the product. For a WinForms application, it seems like intercepting the `WM_GESTURENOTIFY` and then calling `SetGestureConfig` in order to receive the `WM_GESTURE` message is the way to go. The [MSDN documentation](https://docs.microsoft.com/en-gb/windows/desktop/wintouch/wm-gesture) for this message includes some barebones sample code in C++ - this might be of help. I _really_ don't have any time right now but this is interesting enough and ties in with another mini-project I want to do, so I'll look into this - but it probably won't be for a few weeks. 

Regards;
Richard Moss

**Comment by a1880** [comment]
Thanks for your motivating reply.

Greetings,

Axel Kemper
